version: "3.8"

services:
  meshroom:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - C:\meshroom_data/input:/input
      - C:\meshroom_data/output:/output
    working_dir: /meshroom
    command:
      ["python3", "meshroom_batch", "--input", "/input", "--output", "/output"]
